[tool.poetry]
name = "piratepunisher"
version = "0.1.0"
description = "Minimal PiratePunisher demo"
authors = ["dev"]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.dev-dependencies]
pytest = "*"
